version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
platform: x64
image: 
  - Ubuntu
  - Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
install:
  - sh: echo oracle-java10-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  - sh: sudo add-apt-repository ppa:linuxuprising/java
  - sh: sudo apt update
  - sh: sudo apt install -y oracle-java10-installer
  - sh: sudo apt install -y oracle-java10-set-default
  - sh: export JAVA_HOME=/usr/lib/jvm/java-10-oracle
  - sh: echo java home is $JAVA_HOME
  - sh: sudo apt install -y fakeroot
  - ./gradlew -version
build_script:
  - ./gradlew build -x test
after_build:
  - ./gradlew deploy
artifacts:
  - path: build\libs\MapTool-*.jar
    name: MapTool-Jar
  - path: releases\release-*\MapTool-*.exe
    name: MapTool-Windows
  - path: releases\release-*\MapTool-*.deb
    name: MapTool-Linux
deploy:
  - provider: GitHub
    description: Windows release from AppVeyor
    auth_token:
      secure: HXIHe/F7K2yGOZ0I56DW5PevrQDe+zjyunjORGKYaUGxFtvPYPcmOdjZT69tzHcS
    artifact: MapTool-Jar, MapTool-Windows, MapTool-Linux
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
notifications:
  - provider: Webhook
    url: 
      secure: AYQNchUXucpUxTDKoURYmnesdyYxxAPeGmGf0tM/aJhGVp8X5yuiKoZNjULxjoOICX47ufGpdz+BEJ9nYaj7WrBSNx5dJJOoxsZ+dpPZfPOlidHW/JoNWHM8JMP0P5TwRGaTOGOk3aIlUBftDA/wRVQhRcjiwivpoA0mzD6PSsY=
    method: POST
    body: >-
      {
        "embeds": [
          {
            "title": "Build {{buildId}}",
            "url": "{{buildUrl}}",
            "color": {{#passed}}40973{{/passed}}{{^passed}}11672839{{/passed}},
            "footer": {
              "icon_url": "{{#passed}}https://i.imgur.com/Rf4g8v6.png{{/passed}}{{^passed}}https://i.imgur.com/QaERwAW.png{{/passed}}",
              "text": "{{#passed}}Success{{/passed}}{{^passed}}Failure{{/passed}}"
            },
            "author": {
              "name": "{{commitAuthor}}",
              "url": "https://github.com/{{repositoryName}}/commit/{{commitId}}"
            },
            "fields": [
              {
                "name": "Commit",
                "value": "[{{commitMessage}}](https://github.com/{{repositoryName}}/commit/{{commitId}})"
              },
              {
                "name": "Duration",
                "value": "{{duration}}",
                "inline": true
              },
              {
                "name": "Build version",
                "value": "{{buildVersion}}",
                "inline": true
              }
            ]
          }
        ]
      }
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
