language: java
sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode10
script: 
  - ./gradlew build -x test
before_deploy:
 - ./gradlew deploy
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_KEY
  file_glob: true
  file: releases/release-*/*
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  draft: true
  on:
    repo: $REPO
    tags: true
    all_branches: true
notifications:
  webhooks:
    on_success:
      - wget $TRAVIS_DISCORD_WEBHOOK_SCRIPT_URL
      - chmod +x send.sh
      - ./send.sh success $DISCORD_URL
    on_failure:
      - wget $TRAVIS_DISCORD_WEBHOOK_SCRIPT_URL
      - chmod +x send.sh
      - ./send.sh failure $DISCORD_URL